-- Ajouter les nouvelles valeurs d'enum
ALTER TYPE "DocumentStatut" ADD VALUE IF NOT EXISTS 'BROUILLON';
ALTER TYPE "DocumentStatut" ADD VALUE IF NOT EXISTS 'REDACTION';
ALTER TYPE "DocumentStatut" ADD VALUE IF NOT EXISTS 'RELECTURE';
ALTER TYPE "DocumentStatut" ADD VALUE IF NOT EXISTS 'VALIDATION';
ALTER TYPE "DocumentStatut" ADD VALUE IF NOT EXISTS 'FINALISATION';
